import Head from 'next/head';

import { Component } from '@/components/global/component';
import { Layout } from '@/components/global/layout';
import { Home } from '@/components/home';

const Index: Component = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name={'description'} content={'Generated by create next app'} />
        <link rel={'icon'} href={'/favicon.ico'} />
      </Head>

      <Layout>
        <Home />
      </Layout>
    </>
  );
};

export default Index;
