import Head from 'next/head';
import Layout from './../components/global/layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <h1>It&apos;s a holiday?</h1>
        <p>Not today!</p>
      </Layout>
    </>
  );
}
