import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <nav>
          <Link href='/'>Home</Link>
          <Link href='/all'>All holidays</Link>
        </nav>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>It&apos;s a holiday?</h1>

        <p className={styles.description}>Not today!</p>
      </main>

      <footer className={styles.footer}>
        <div className={styles.wrapper}>
          <p>
            Created by <a href='https://jahir.dev'>Jahir Fiquitiva</a>
          </p>
          <p>
            Heavily inspired by <a href='https://srhart.co/'>Sr. Hart</a>&apos;s{' '}
            <a href='https://esfestivo.co/'>esfestivo</a> project
          </p>
        </div>
      </footer>
    </div>
  );
}
