import Head from 'next/head';
import Home from '../components/home/home';
import Layout from './../components/global/layout';

export default function Index(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <Home />
      </Layout>
    </>
  );
}
